source ~/.aliases/color_aliases
source ~/.aliases/dotfile_aliases
source ~/.aliases/git_aliases
source ~/.aliases/ls_aliases
source ~/.aliases/xmonad_aliases

# State of computer
alias sus='sudo pm-suspend'


# Terminal aliases 
alias c='clear'
alias h='history'
alias x='exit'


# Navigating direct+ories
alias cd='cdls'
alias hm='cd $HOME'
alias m='cd /media/$USER'
alias dr='cd $HOME/Dropbox'
alias sa='de $HOME/work/sagio'

alias ..='cd ..'
alias ...='cd ...'
alias ....='cd ....'
alias .....='cd .....'


alias lo='/opt/ibm/ILOG/CPLEX_Studio1251/opl/oplide/oplide &'


# apt-get
alias install='packer -S'
alias update='sudo pacman -Syu'
alias remove='sudo pacman -R'

# Open files easily.
alias open='xdg-open'

# Emacs
alias emacs='emacs --no-window-system'
alias e='emacs'

# Trying to start using emacs instead of vim
# alias vim='emacs'

# Productivity stuff
alias wf="emacs $WORKFLOW_FILE"
alias jn="emacs $JOURNAL_FILE"

# Size of stuff in current dir
alias s='du -sh *'

# Network
alias ping1='ping -c 4 google.com'
alias ping2='ping -c 4 192.168.0.1'

# Exercise
alias exercise="open $HOME/personal/exercising.ods"

alias topdf='unoconv -fpdf '

alias fix_screen='xrandr --auto && xrandr --output VGA1 --right-of LVDS1'
