# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#

templates:
  params:
    author-name: Tom Sydney Kerckhove
    author-email: syd.kerckhove@gmail.com
    copyright: 'Copyright: (c) 2016 Tom Sydney Kerckhove'
    github-username: NorfairKing
