# This file is sourced at any zsh interavtive shell
debug "sourcing .zshrc"
indent

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

# Plugins
plugins=()

# Use case-sensitive completion
CASE_SENSITIVE="true"

# No autocorrection
unsetopt correct_all 

safe_source $ZSH/oh-my-zsh.sh
safe_source ~/.aliases/aliases

if [[ "$(which hastory)" != "hastory not found" ]]
then
  source <(hastory generate-gather-wrapper-script)
fi

precmd() {
  hastory_gather_
}

autoload bashcompinit
bashcompinit

make_completion() {
  local bin=~/.local/bin/$1

  if [[ "$(which ${bin})" == "${bin} not found" ]]
  then
    return 0
  fi

  source <(${bin} --bash-completion-script ${bin})
}
make_completion stack
make_completion hastory
make_completion super-user-spark
make_completion donna
make_completion wolf
make_completion smos-query

DISABLE_UPDATE_PROMPT=true

if [[ -d /nix ]]
then
  source /etc/profile.d/nix.sh
  source /etc/profile.d/nix-daemon.sh
fi


outdent
