version: '{build}'
environment:
  matrix:
  - arch: 32
  - arch: 64
install:
  - git submodule update --init --recursive
  - ps: $env:python = if ($env:arch -eq 32) { 'C:\Python27' } else { 'C:\Python27-x64' }
  - appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
  - set PATH=%python%;%python%\Scripts;%PATH%
  - python get-pip.py
  - pip install -r python\test_requirements.txt
build_script:
  - python run_tests.py
# Disable automatic tests
test: off
