contexts:
  home: 'ancestor:tag:(home or (online or offline))'
  transport: '(not:ancestor:tag:home and ancestor:tag:(transport or offline))'
  airplane: '(not:ancestor:tag:(online or home) and ancestor:tag:offline)'
  toast: 'ancestor:tag:toast'

waiting:
  threshold: 7

work:
  time-filter: timewindow
  checks:
    - property:timewindow
  columns:
    - file
    - state
    - header
    - property:timewindow
  sorter: '(reverse:property-as-time:timewindow then file)'

sync:
  server-url: "api.staging.smos.cs-syd.eu"
  username: syd
  password: smos-password-test

scheduler:
  schedule:
  - template: templates/fpco-weekly.smos
    destination: projects/fpco/work-%V.smos
    schedule: "0 10 * * 0" # “At 10:00 on Sunday.”

