# This file is sourced at any zsh interavtive shell

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Plugins
plugins=(git wd)

PROMPT_COMMAND="$PROMPT_COMMAND; pwd >> $HOME/.latest_dirs"
precmd() { eval "$PROMPT_COMMAND" }

source $ZSH/oh-my-zsh.sh

if [ -f ~/.aliases/aliases ]; then
    source ~/.aliases/aliases
fi

source ~/.paths/paths


# TODO explain this?
unsetopt correct_all 

# Makes sure the emacs server starts when needed
export ALTERNATE_EDITOR=""

