" TODO, this all needs info
call pathogen#infect()

" Enable syntax highlighting
syntax on 

filetype plugin indent on

" size of a hard tabstop
set tabstop=2

" size of an "indent"
set shiftwidth=2

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=2

" make "tab" insert indents instead of tabs at the beginning of a line
set smarttab

" always uses spaces instead of tab characters
set expandtab


autocmd FileType haskell setlocal shiftwidth=4 tabstop=4 softtabstop=4
let g:ycm_semantic_triggers = {'haskell' : ['.']}

" No more arrow keys
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>
imap <Left> <Nop>
imap <Right> <Nop>
imap <Up> <Nop>
imap <Down> <Nop>

set backspace=indent,eol,start

let mapleader=","

set encoding=utf-8
set t_Co=256

set rtp+=$HOME/.local/lib/python3.3/site-packages/powerline/bindings/vim/
let g:Powerline_symbols = "fancy"
set laststatus=2


" Powerline fonts in airline
let g:airline_powerline_fonts = 1

colorscheme wombat

" For YouCompleteMe
set completeopt=menuone


" For the notes, compile, generate tex and compile tex in one command
map ,. :w<CR>:!make -B --directory=~/the-notes bin && cd ~/the-notes && ./current <CR><CR>
map ,p :w<CR>:!make -B --directory=~/the-notes bin && cd ~/the-notes && ./current <CR>

map ms :%s/\.\(\s\+\|$\)/.\r\r/g


" cross product
digraph cp 10799 

" Supremum and infimum
digraph lb 8851
digraph ub 8852


" delete trailing whitespace on save
fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun

autocmd FileType c,cpp,java,php,ruby,python,haskell autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

" Close vim entirely
map :q :qa

" move between buffers with just C-w
map <C-w> :wincmd p<CR>
