" TODO, this all needs info
call pathogen#infect()

" Enable syntax highlighting
syntax on 

filetype plugin indent on

" size of a hard tabstop
set tabstop=2

" size of an "indent"
set shiftwidth=2

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=2

" make "tab" insert indents instead of tabs at the beginning of a line
set smarttab

" always uses spaces instead of tab characters
set expandtab

" No more arrow keys
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>
imap <Left> <Nop>
imap <Right> <Nop>
imap <Up> <Nop>
imap <Down> <Nop>

set backspace=indent,eol,start

let mapleader=","

set encoding=utf-8
set t_Co=256

set rtp+=$HOME/.local/lib/python3.3/site-packages/powerline/bindings/vim/
let g:Powerline_symbols = "fancy"
set laststatus=2


" Powerline fonts in airline
let g:airline_powerline_fonts = 1

colorscheme wombat

" For YouCompleteMe
set completeopt=menuone



map ,. :w<CR>:!make --directory=~/the-notes generate <CR><CR>
map ,p :w<CR>:!make --directory=~/the-notes generate <CR>

map ms :%s/\.\(\s\+\|$\)/.\r\r/g


" cross product
digraph cp 10799 


" delete trailing whitespace on save
fun! <SID>StripTrailingWhitespaces()
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfun

autocmd FileType c,cpp,java,php,ruby,python,haskell autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

