# This file is sourced at any zsh interavtive shell
debug "sourcing .zshrc"
indent

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

# Plugins
plugins=(taskwarrior wd)

# Use case-sensitive completion
CASE_SENSITIVE="true"

# No autocorrection
unsetopt correct_all 

precmd() {
  eval "$PROMPT_COMMAND"
  pwd >> $HOME/.latest_dirs

  if [[ "$(id -u)" -ne "0" ]]
  then
    mkdir -p ~/.logs
    echo "$(date +%Y-%m-%d.%H:%M:%S) $(pwd) $(history | tail --lines=1)" >> "$HOME/.logs/shell-history-$(date +%Y-%m-%d).log"
  fi
}


safe_source $ZSH/oh-my-zsh.sh
safe_source ~/.aliases/aliases

outdent


projects=$(projects_without_next_action.sh)
if [ "$projects" != "" ]
then
  print_colored_text RED "Attention: The following projects don't currently have a next action:\n"
  echo $projects
  echo
fi

waiting=$(task +waiting +PENDING count)
if [ "$waiting" != "0" ]
then
  print_colored_text BLUE "Any progress on these waiting-fors?\n"
  task +waiting +PENDING ls
fi
