" TODO, this all needs info
call pathogen#infect()

" Enable syntax highlighting
syntax on 

filetype plugin indent on

" size of a hard tabstop
set tabstop=4

" size of an "indent"
set shiftwidth=4

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=4

" make "tab" insert indents instead of tabs at the beginning of a line
set smarttab

" always uses spaces instead of tab characters
set expandtab

" No more arrow keys
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>
imap <Left> <Nop>
imap <Right> <Nop>
imap <Up> <Nop>
imap <Down> <Nop>

set backspace=indent,eol,start

let mapleader=","

set encoding=utf-8
set t_Co=256

set rtp+=$HOME/.local/lib/python3.3/site-packages/powerline/bindings/vim/
let g:Powerline_symbols = "fancy"
set laststatus=2

colorscheme wombat

" Renaming
" For local replace
nnoremap gr gd[{V%:s/<C-R>///gc<left><left><left>

" For global replace
nnoremap gR gD:%s/<C-R>///gc<left><left><left>
