xset -dpms
xset s off

# set the cursor
xsetroot -cursor_name left_ptr

# add resources
xrdb -merge ~/.Xresources

# screen settings
source ~/.screen

# start xmonad
exec xmonad --keyboard laptop.dvorak 
