xset -dpms
xset s off

# set the cursor
xsetroot -cursor_name left_ptr

# set dvorak layout
xmodmap ".keyboards/current"

# set retype speed
xset r rate 250 30

# add resources
xrdb -merge ~/.Xresources

# screen settings
source ~/.screen

# Redshift
redshift -l 50:0 &

# start xmonad
exec xmonad --keyboard laptop.dvorak
