xset -dpms
xset s off

# set the cursor
xsetroot -cursor_name left_ptr

# Set the appropriate keyboard layout
xmodmap ~/.keyboards/current

# set retype speed
xset r rate 250 30

# add resources
xrdb -merge ~/.Xresources

# Start redshift
redshift -l 50:0

# start xmonad
~/.xmonad/xmonad
